### ISSUE TITLE
Search Crashing on no text input,

### ISSUE THREAD

**Issue by dtlaurianti** [uiowahjmjohnsonselt2023/matts-marketplace#57]
**Describe the bug**

**To Reproduce**
1. Go to Buy tab
2. Type nothing in the search bar
3. Search

**Expected behavior**
Should just search filtering by category or price - the category buttons at the bottom of the home page do work properly.

**Screenshots**
![image](https://github.com/uiowahjmjohnsonselt2023/matts-marketplace/assets/71203230/f8d7b371-d998-4b08-a3ad-aee58965f502)

**Comment by mattsperanza** [comment]
This is caused by commit 43f112e955b1bdad5141bf4cb6b74a694ef55981 where the permitted params[:category] --> params[:category_id] for unknown reasons... I think it was because that is what it it looks like in the db schema for the items model, but category_id doesn't really make sense because we only have 5.
